#!/bin/bash
# Copyright 2016 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Runs mount-passthrough with minijail0 as chronos.

# shellcheck source=mount-passthrough-jailed-utils.sh
. /usr/share/arc/mount-passthrough-jailed-utils.sh

run_mount_passthrough_with_minijail0 "$@"
