#!/bin/bash
# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Runs mount-passthrough with minijail0 as chronos. The owner of the files
# in FUSE is set to Android's MediaProvider (whose UID is specified as an
# argument), wherease their GID is set to Android's external_storage (1077).
# Expected to be used for mount-passthrough processes for files shared with
# ARCVM using virtio-fs.

# shellcheck source=mount-passthrough-jailed-utils.sh
. /usr/share/arc/mount-passthrough-jailed-utils.sh

# Android's external_storage GID (not shifted).
ANDROID_EXTERNAL_STORAGE_GID=1077

# Set UID and GID in FUSE to Android's MediaProvider and external_storage, resp.
set -- "$@" --fuse_gid="${ANDROID_EXTERNAL_STORAGE_GID}"

# Enter the concierge namespace.
set -- "$@" --enter_concierge_namespace

# Set the maximum number of open file descriptors to 262144.
# The number is taken from vm_concierge.conf, which defines the maximum number
# of fds that can be opened by virtio-fs devices.
# We specify the same number here because files opened by this mount-passthrough
# process are expected to be the ones opend by a virtio-fs device, and we'd like
# to let virtio-fs devices open as many files as they like without imposing a
# new restriction on the number of files they can open.
set -- "$@" --max_number_of_open_fds=262144

run_mount_passthrough_with_minijail0 "$@"
