# proto-file: chromiumos/build/api/subtools.proto
# proto-message: chromiumos.build.api.SubtoolPackage
# https://chrome-infra-packages.appspot.com/p/chromiumos/infra/tools/delta_generator
name: "delta_generator"
type: EXPORT_CIPD
max_files: 200
paths: [
  {
    input: "/usr/bin/delta_generator"
  }
]
