// Copyright 2024 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef METRICS_STRUCTURED_METRICS_CLIENT_STRUCTURED_EVENTS_H_
#define METRICS_STRUCTURED_METRICS_CLIENT_STRUCTURED_EVENTS_H_

#include <stdio.h>

namespace metrics_client {

// Helper for the "--structured" argument for the metrics_client command line.
// Parses the remaining arguments after "--structured" and sends the structured
// metric.
//
// Expects that the metrics::structured::RecorderSingleton has already been set
// up.
//
// Parameters:
//   |argc|, |argv|: The command line of the program.
//   |current_arg|: the index of the argument after "--structured" within argv.
//   |err|: The FILE* to write error messages to. Normally stderr but can be
//          overridden for testing.
//
// NOTE: The definition for this function is autogenerated by
// metrics/structured/gen_events.py.
int SendStructuredMetric(int argc,
                         const char* const argv[],
                         int current_arg,
                         FILE* err);

}  // namespace metrics_client
#endif  // METRICS_STRUCTURED_METRICS_CLIENT_STRUCTURED_EVENTS_H_
