// Copyright 2022 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef DIAGNOSTICS_BINDINGS_CONNECTIVITY_DATA_GENERATOR_H_
#define DIAGNOSTICS_BINDINGS_CONNECTIVITY_DATA_GENERATOR_H_

namespace diagnostics {
namespace bindings {
namespace connectivity {

template <typename T>
class DataGeneratorInterface {
 public:
  using Type = T;
  // Generates T for TestConsumer and TestProvider to test the parameters. This
  // should return value even if |HasNext()| is false.
  virtual T Generate() = 0;
  // Returns true if there are values need to be generated by |Generate|. Most
  // of the cases this only returns true before the first |Generate|. Some types
  // require more than one |Generate| to test different values.
  virtual bool HasNext() = 0;
};

}  // namespace connectivity
}  // namespace bindings
}  // namespace diagnostics

#endif  // DIAGNOSTICS_BINDINGS_CONNECTIVITY_DATA_GENERATOR_H_
