// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef VM_TOOLS_CROS_IM_BACKEND_TEXT_INPUT_ENUMS_H_
#define VM_TOOLS_CROS_IM_BACKEND_TEXT_INPUT_ENUMS_H_

// Enum definitions from the text-input protocol. These should remain in sync
// with the definitions in text-input-unstable-v1.xml and thus those generated
// in text-input-unstable-v1-client-protocol.h.

// Having these enums separated from the generated Wayland headers allows
// frontends to not need a dependency on the Wayland headers, which the backend
// otherwise abstracts away.

// TODO(timloh): Add some sort of checks to ensure these are kept in sync.

#ifndef ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ENUM
#define ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ENUM
enum zwp_text_input_v1_preedit_style {
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_DEFAULT = 0,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_NONE = 1,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ACTIVE = 2,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_INACTIVE = 3,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_HIGHLIGHT = 4,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_UNDERLINE = 5,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_SELECTION = 6,
  ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_INCORRECT = 7,
};
#endif  // ZWP_TEXT_INPUT_V1_PREEDIT_STYLE_ENUM

#ifndef ZWP_TEXT_INPUT_V1_CONTENT_HINT_ENUM
#define ZWP_TEXT_INPUT_V1_CONTENT_HINT_ENUM
enum zwp_text_input_v1_content_hint {
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_NONE = 0x0,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_DEFAULT = 0x7,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_PASSWORD = 0xc0,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_AUTO_COMPLETION = 0x1,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_AUTO_CORRECTION = 0x2,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_AUTO_CAPITALIZATION = 0x4,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_LOWERCASE = 0x8,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_UPPERCASE = 0x10,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_TITLECASE = 0x20,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_HIDDEN_TEXT = 0x40,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_SENSITIVE_DATA = 0x80,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_LATIN = 0x100,
  ZWP_TEXT_INPUT_V1_CONTENT_HINT_MULTILINE = 0x200,
};
#endif /* ZWP_TEXT_INPUT_V1_CONTENT_HINT_ENUM */

#ifndef ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ENUM
#define ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ENUM
enum zwp_text_input_v1_content_purpose {
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_NORMAL = 0,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ALPHA = 1,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_DIGITS = 2,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_NUMBER = 3,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_PHONE = 4,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_URL = 5,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_EMAIL = 6,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_NAME = 7,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_PASSWORD = 8,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_DATE = 9,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_TIME = 10,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_DATETIME = 11,
  ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_TERMINAL = 12,
};
#endif /* ZWP_TEXT_INPUT_V1_CONTENT_PURPOSE_ENUM */

#endif  // VM_TOOLS_CROS_IM_BACKEND_TEXT_INPUT_ENUMS_H_
