# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

mno {
  data {
    uuid: "d433d22c-02ac-43b5-b2b3-91f96c4b2d7a"
    country: "zz"
    localized_name {
      name: "Test Network - Hotspot"
    }
    mccmnc: "00101"
    tethering_allowed: true
    mobile_apn {
      is_required_by_carrier_spec: true
      apn: "callbox-dun-ipv4v6"
      ip_type: IPV4V6
      type: DEFAULT
      type: IA
      type: DUN
    }
  }
}

mno {
  data {
    uuid : "29312b25-e5c7-47cc-b83c-32f9a10437d3"
    country : "es"
    localized_name {
      name : "Movistar (Telefónica) - Hotspot"
    }
    mccmnc : "21405"
    mccmnc : "21407"
    tethering_allowed: true
    mobile_apn {
      apn : "telefonica.es"
      localized_name {
        name : "Telefónica"
      }
      username : "telefonica"
      password : "telefonica"
      type : DEFAULT
      type : DUN
    }
  }
}

mno {
  data {
    uuid : "3c0341da-65f3-49f5-83c8-4d864b4e165e"
    country : "pl"
    localized_name {
      name : "Orange"
    }
    mccmnc : "26003"
    tethering_allowed: true
    mobile_apn {
      apn : "internet"
      localized_name {
        name : "Standard access - with image compression"
      }
      localized_name {
        name : "Dostęp standardowy - z kompresją grafiki"
      }
      username : "internet"
      password : "internet"
      type : DEFAULT
    }
  }
}

mno {
  data {
    uuid : "61a4d944-e4cf-49d3-b674-ab7fc4e82e69"
    country : "fr"
    localized_name {
      name : "Free Mobile"
    }
    mccmnc : "20815"
    tethering_allowed: true
    mobile_apn {
      apn : "free"
      localized_name {
        name : "Free-Mobile"
      }
      username : "free"
      password : "free"
      type : DEFAULT
    }
  }
}
