// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

//! Include the FFI bindings for the HAL generated by bindgen.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
