#!/bin/sh

# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Configures cpufreq if /etc/cpufreq.conf exists and contains valid
# configuration data.

# Convenience variables with sysfs paths.
CPU_BASE_DIR=/sys/devices/system/cpu
CPUFREQ_DIR="${CPU_BASE_DIR}/cpufreq"

error() {
  echo "$*" 1>&2
}

##############################################
# Sets the cpufreq governor for all CPUs.
# Globals:
#   CPU_BASE_DIR
# Arguments:
#   Name of the cpufreq governor
# Returns:
#   nothing
##############################################
cpufreq_set_governor() {
  local governor="$1"
  local cpu
  local ret=0

  for cpu in "${CPU_BASE_DIR}"/cpu[0-9]*; do
    if [ -e "${cpu}/cpufreq" ]; then
      echo "${governor}" > "${cpu}/cpufreq/scaling_governor" || {
        ret="$?"
        error "Failed to set ${cpu} governor to ${governor}"
      }
    fi
  done

  return "${ret}"
}

###########################################################################
# Gets the value of a configuration setting for the cpufreq governor.
# The settings are specified in the configuration file.
# Arguments:
#   Name of the sysfs attribute of the setting
# Returns:
#   Value of the requested setting, or an empty string if the setting is
#   not specified in the configuration file.
###########################################################################
governor_get_config_value() {
  local setting="$1"
  local conf_var

  conf_var="CPUFREQ_$(echo "${setting}" | tr "[:lower:]" "[:upper:]")"

  echo "$(eval "echo \$$conf_var")"
}

#############################################################################
# Configures a setting of the cpufreq governor on systems with a single
# cpufreq policy. Does nothing if the setting is not specified in the
# configuration file.
# Globals:
#   GOVERNOR_DIR
# Arguments:
#   Name of the sysfs attribute of the setting
# Returns:
#   nothing
###########################################################################
governor_set_optional() {
  local setting="$1"
  local sysfs_attr

  sysfs_attr="${GOVERNOR_DIR}/${setting}"
  if [ ! -f "${sysfs_attr}" ]; then
    return
  fi

  local value="$(governor_get_config_value "${setting}")"
  if [ -z "${value}" ]; then
    return
  fi

  echo "${value}" > "${sysfs_attr}"
}

######################################################################
#
# Interactive governor
#
#############################################################################
# Configures the interactive cpufreq governor according to the values
# from the configuration file.
# Globals:
#   GOVERNOR_DIR
#   CPUFREQ_DIR
# Arguments:
#   None
# Returns:
#   nothing
#########################################################################
cpufreq_config_interactive() {
  local setting
  local ret=0

  GOVERNOR_DIR="${CPUFREQ_DIR}/interactive"
  if [ -d "${GOVERNOR_DIR}" ]; then
    for setting in input_boost above_hispeed_delay go_hispeed_load \
        hispeed_freq min_sample_time target_loads timer_rate; do
      governor_set_optional "${setting}" || {
        ret="$?"
        error "Failed to set interactive setting ${setting}"
      }
    done
  fi

  return "${ret}"
}


######################################################################
#
# Ondemand governor
#
#########################################################################
# Configures the ondemand cpufreq governor according to the values
# from the configuration file.
# Globals:
#   GOVERNOR_DIR
# Arguments:
#   None
# Returns:
#   nothing
#########################################################################
cpufreq_config_ondemand() {
  local setting
  local ret=0

  GOVERNOR_DIR="${CPUFREQ_DIR}/ondemand"
  for setting in sampling_rate up_threshold ignore_nice_load \
      io_is_busy sampling_down_factor powersave_bias; do
    governor_set_optional "${setting}" || {
      ret="$?"
      error "Failed to set ondemand setting ${setting}"
    }
  done

  return "${ret}"
}

######################################################################

if [ ! -f /etc/cpufreq.conf ]; then
  exit 0
fi
. /etc/cpufreq.conf

ret=0

if [ -z "${CPUFREQ_GOVERNOR}" ]; then
  if dump_power_status | grep -q 'battery_status Discharging'; then
    CPUFREQ_GOVERNOR="${CPUFREQ_GOVERNOR_BATTERY_DISCHARGE}"
  else
    CPUFREQ_GOVERNOR="${CPUFREQ_GOVERNOR_BATTERY_CHARGE}"
  fi
fi

if [ -z "${CPUFREQ_GOVERNOR}" ]; then
  exit 0
fi

cpufreq_set_governor "${CPUFREQ_GOVERNOR}" || ret="$?"

if [ "${CPUFREQ_GOVERNOR}" = "interactive" ]; then
  cpufreq_config_interactive
elif [ "${CPUFREQ_GOVERNOR}" = "ondemand" ]; then
  cpufreq_config_ondemand
fi || ret="$?"

# Set SELinux contexts for the newly created files (if any)
if [ -f /sys/fs/selinux/enforce ]; then
  /sbin/restorecon -R "${CPUFREQ_DIR}" || {
    ret="$?"
    error "restorecon failed"
  }
fi

exit "${ret}"
